"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Copy, Loader2, X } from "lucide-react";
type Method={_id:string;name:string;type:"bank"|"wallet";currency:"NGN"|"USD"|"BTC";institution:string;accountName:string;accountNumber?:string;walletAddress?:string;instructions?:string};
export default function InvestmentModal({open,onClose,onDone}:{open:boolean;onClose:()=>void;onDone:()=>void}){
 const [methods,setMethods]=useState<Method[]>([]);const [selected,setSelected]=useState<Method|null>(null);const [amount,setAmount]=useState("");const [reference,setReference]=useState("");const [note,setNote]=useState("");const [loading,setLoading]=useState(false);const [success,setSuccess]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(open)fetch("/api/payment-methods").then(r=>r.json()).then(d=>setMethods(d.methods||[]));},[open]);
 if(!open)return null;
 async function submit(){setError("");if(!selected)return setError("Choose a payment method.");if(Number(amount)<5000&&selected.currency==="USD")return setError("The minimum investment is $5,000.");if(!reference)return setError("Enter your payment reference or transaction ID.");setLoading(true);try{const r=await fetch("/api/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentMethodId:selected._id,amount:Number(amount),reference,note})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to submit");setSuccess(true);onDone()}catch(e){setError(e instanceof Error?e.message:"Unable to submit payment.")}finally{setLoading(false)}}
 return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X/></button>{success?<div className="success-view"><div className="success-icon"><CheckCircle2/></div><h2>Payment submitted</h2><p>Your payment is pending verification. You will receive an in-app notification when it is reviewed.</p><button className="btn btn-gold btn-block" onClick={onClose}>Done</button></div>:<><div className="modal-head"><div className="section-kicker">NEW INVESTMENT</div><h2>Fund your investment</h2><p>Select the account or wallet you want to use.</p></div>{error&&<div className="alert error">{error}</div>}<div className="method-grid">{methods.map(m=><button key={m._id} className={`method ${selected?._id===m._id?"selected":"" : ""}`} onClick={()=>setSelected(m)}><span className="method-currency">{m.currency}</span><b>{m.name}</b><small>{m.institution}</small></button>)}</div>{selected&&<div className="payment-details"><div className="detail-title">{selected.type==="bank"?"Bank transfer details":"Wallet details"}</div><div className="detail-row"><span>Account name</span><b>{selected.accountName}</b></div>{selected.accountNumber&&<div className="detail-row"><span>Account number</span><b>{selected.accountNumber} <Copy size={14} onClick={()=>navigator.clipboard.writeText(selected.accountNumber||"")}/></b></div>}{selected.walletAddress&&<div className="detail-row"><span>Wallet address</span><b className="wrap">{selected.walletAddress}</b></div>}<p>{selected.instructions}</p></div>}<label>Amount ({selected?.currency||"currency"})<input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={selected?.currency==="USD"?"5000":"Enter amount"}/></label><label>Payment reference / transaction ID<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="e.g. TRX-123456"/></label><label>Optional note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything our verification team should know?"/></label><button className="btn btn-gold btn-block" disabled={loading||!selected} onClick={submit}>{loading?<Loader2 className="spin"/>:"I have made the payment"}</button></>}</div></div>
}
