"use client";
import { useEffect,useState } from "react"; import { ArrowUpRight, Clock3, ShieldCheck, WalletCards } from "lucide-react"; import InvestmentModal from "@/components/InvestmentModal"; import {money,dateTime} from "@/lib/format";
export default function Dashboard(){const [user,setUser]=useState<any>(null),[payments,setPayments]=useState<any[]>([]),[investments,setInvestments]=useState<any[]>([]),[open,setOpen]=useState(false);
async function load(){const [u,p,i]=await Promise.all([fetch("/api/me"),fetch("/api/payments"),fetch("/api/investments")]);setUser((await u.json()).user);setPayments((await p.json()).payments||[]);setInvestments((await i.json()).investments||[])}useEffect(()=>{load()},[]);
return <div className="dashboard-page"><div className="container-app"><div className="welcome-row"><div><span className="section-kicker">ACCOUNT OVERVIEW</span><h1>Your investment dashboard</h1><p className="muted">Monitor balances, investments and payment activity in one place.</p></div><button className="btn btn-gold" onClick={()=>setOpen(true)}><ArrowUpRight size={17}/> I want to invest</button></div>
<div className="balance-grid"><div className="balance-card main"><div><span>Available balance</span><strong>{user?.balances?.USD?money(user.balances.USD,"USD"):"$0.00"}</strong><small>USD balance</small></div><WalletCards/></div><div className="balance-card"><span>Invested balance</span><strong>{user?.balances?.NGN?money(user.balances.NGN,"NGN"):"₦0.00"}</strong><small>NGN balance</small></div><div className="balance-card"><span>Active investments</span><strong>{investments.filter(i=>i.status==="active").length}</strong><small>Current positions</small></div></div>
<div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h3>Recent investments</h3><p>Latest approved investment activity</p></div><a href="/dashboard/investments">View all</a></div>{investments.slice(0,4).map(i=><div className="activity-row" key={i._id}><div className="activity-icon"><TrendingIcon/></div><div><b>{i.currency} {i.amount.toLocaleString()}</b><span>{dateTime(i.createdAt)}</span></div><strong className="status active">{i.status}</strong></div>)}{!investments.length&&<Empty text="Your approved investments will appear here."/>}</section><section className="panel"><div className="panel-head"><div><h3>Payment activity</h3><p>Verification history</p></div></div>{payments.slice(0,4).map(p=><div className="activity-row" key={p._id}><div className="activity-icon"><Clock3/></div><div><b>{p.amount.toLocaleString()} {p.currency}</b><span>{p.reference}</span></div><strong className={`status ${p.status}`}>{p.status}</strong></div>)}{!payments.length&&<Empty text="No payment activity yet."/>}</section></div>
<div className="security-banner"><ShieldCheck/><div><b>Verification matters</b><p>Payments are reviewed by an administrator before an investment becomes active. Never send funds to an address that is not shown in your authenticated Trust Chain account.</p></div></div></div><InvestmentModal open={open} onClose={()=>{setOpen(false);load()}} onDone={load}/></div>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>} function TrendingIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m3 17 6-6 4 4 7-8"/><path d="M14 7h6v6"/></svg>}
